[package]
name = "cargo-flatpak"
version = "0.0.1"
edition = "2021"
description = "TODO"
license = "Apache-2.0/MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
